### ISSUE TITLE
Update contributions and participate in Hacktoberfest2019

### ISSUE THREAD

**Issue by elangosundar** [10secondsofcode/10secondsofcode#13]
# Welcome to HacktoberFest 2019 event from #10secondsofcode
Follow these steps to make your first pull request-
  1. Fork this repository.
  2. Clone your forked repository to your local machine.
  3. Add your name in Contributors.md file.
  4. Write these command on your terminal-
  ```
  git add -A
  git commit -m "your name"
  git push origin master
  ```
  5. Then create your pull request.
  6. Star my repository.
  7. Congratulations!! You have successfully created your pull request.
  8. Check your progress here (https://hacktoberfest.digitalocean.com/profile)
  Wait for your shirt.

**Comment by kev1nboer** [comment]
PR Added: #14

**Comment by orimdominic** [comment]
If merged, please close. Thanks
