### ISSUE TITLE
Create LOGO for 10secondsofcode 

### ISSUE THREAD

**Issue by 10-seconds** [10secondsofcode/10secondsofcode#36]
# Create LOGO for 10secondsofcode 

1. Create the logo for 10secondsofcode and and it will bring the meaning of `10seconds` understanding the concepts.
2. Use your creativity and design.

**Comment by hannesfant** [comment]
Mind if I jump on this?

**Comment by jams008** [comment]
I added the logo

**Comment by 10-seconds** [comment]
> Mind if I jump on this?

Sure....take it

**Comment by mandyellow** [comment]
Hello 🦊 I create a logo for your project with a meaning of "fast", hope you like!

![image](https://user-images.githubusercontent.com/30158643/66257481-7844be00-e7a2-11e9-92f2-554a672d6517.png)

**Comment by elangosundar** [comment]
> Hello  I create a logo for your project with a meaning of "fast", hope you like!
> 
> ![image](https://user-images.githubusercontent.com/30158643/66257481-7844be00-e7a2-11e9-92f2-554a672d6517.png)

@mandyellow It is looking nice and if possible could you please change into https://10seconds.netlify.com theme color like BG - #6156B5 and font color as white..

**Comment by mandyellow** [comment]
Yeah @elangovanshanthi, no problem! If the logo it's okay, I can upload a PNG and SVG version for you. Just tell me where I should upload 😄 

![image](https://user-images.githubusercontent.com/30158643/66260122-ffa22980-e7c2-11e9-81d9-b63871110395.png)

**Comment by elangosundar** [comment]
Nice :) Inside logo folder and we will use it. thanks

**Comment by mandyellow** [comment]
Done! 😄
