### ISSUE TITLE
Read content from markdown file

### ISSUE THREAD

**Issue by 10-seconds** [10secondsofcode/10secondsofcode#51]
Read the content from markdown file in sub pages.

Example : If I am clicking the home page below link like introduction topic , it will redirect topic details page, in this page we have read the introduction markdown file and displaying the content.

1. Goto this page https://10seconds.netlify.com/javascript-objects
2. For this page we have content in https://github.com/10secondsofcode/10secondsofcode/blob/master/src/content/javascript-objects.md.
3. So we have to read the javascript-objects.md file and displaying the content in https://10seconds.netlify.com/javascript-objects.
4. It should works dynamically for all pages like if we add topic in content folder, it will read and displaying content corresponding page.

**Comment by deepansh946** [comment]
Hi, I would love to take this, but can you explain a little bit more about this.

Thanks

**Comment by 10-seconds** [comment]
@deepansh946 thanks.

1. Goto this page https://10seconds.netlify.com/javascript-objects
2. For this page we have content in https://github.com/10secondsofcode/10secondsofcode/blob/master/src/content/javascript-objects.md.
3. So we have to read the javascript-objects.md file and displaying the content in  https://10seconds.netlify.com/javascript-objects.
4. It should works dynamically for all pages like if we add topic in content folder, it will read and displaying content corresponding page.

**Comment by giatuongtran9** [comment]
Hi, I would like to work on this, please

**Comment by 10-seconds** [comment]
> Hi, I would like to work on this, please

sure @giatuongtran9
