### ISSUE TITLE
10secondsofcode PR Welcome

### ISSUE THREAD

**Issue by elangosundar** [10secondsofcode/10secondsofcode#7]
Hi :wave: 

I've created this issue to keep track of things to do for 10secondsofcode. Feel free to pick tasks and create PR if you want. Just add a message below to avoid duplication of work.

Also small PRs that complete one task are easier to review and merge :+1: 

And if you have any question, feel free to ask :)

- [ ] Website template updation
- [ ] Improvement reactjs fucntionality
- [ ] Add reactjs snippets
- [ ] Listout missing functionlities
- [ ] Fix bugs, typos, ... :)

**Comment by luizbaldi** [comment]
Hi @elangovanshanthi,

I was thinking about before develop new features it's a good idea to create a ESLint configuration file and add a Git Hook to keep everything using the same pattern. 

I can do it, what do you think?

**Comment by 10-seconds** [comment]
Sure @luizbaldi . Thanks for your help :) You can create and create the PR.

**Comment by 10-seconds** [comment]
@luizbaldi  can you help to prepare the reactjs snippets and improvement of this repo?

**Comment by luizbaldi** [comment]
@10-seconds Sure! Can you contact me on [Linkedin](https://www.linkedin.com/in/luizbaldi/) or [e-mail](baldilp@gmail.com) to align the demands? I have some ideas but I think it'll be good to clear everything about the project before start coding :)

**Comment by 10-seconds** [comment]
@luizbaldi Did something related to our reactjs snippets?
