### ISSUE TITLE
[Solution] Read the markdown file data into display the content using reactjs

### ISSUE THREAD

**Issue by sarthology** [10secondsofcode/10secondsofcode#8]
It's simple, use npm package [markdown-to-jsx](https://www.npmjs.com/package/markdown-to-jsx).

```
import Markdown from 'markdown-to-jsx';
import React from 'react';
import { render } from 'react-dom';
 
render(<Markdown># Hello world!</Markdown>, document.body);
```

**Comment by 10-seconds** [comment]
@sarthology thanks for your help and i have tried react-markdown. If you have interested could you participate in this repo. Thanks..!
